### ISSUE TITLE
Lobster doesn't recognize member function constness 

### ISSUE THREAD

**Issue by bkayes** [jamesjuett/lobster#291]
```
#include <iostream>

using namespace std;

class test {
  int i;
  test() : i(0) {}
  int func() const {
    i++;
    ++i;
    return i;
  }

  int func2() const {
    i *= 2;
    return i;
  }
};

int main() {
  test t;
  cout << t.func();
  cout << t.func2();
  cout << t.func();
}
```

The above compiles and runs on lobster, which is [confusing to students](https://piazza.com/class/kxxmwqhcnxy2b?cid=3112)

Notice pre/post increment and multiplication (These are the only things I tried, I bet others would not cause it fail compilation either).

**Comment by iteemhe** [comment]
AFAIK, lobster hasn't supported const member functions yet.

![Screen Shot 2022-02-21 at 14 52 32](https://user-images.githubusercontent.com/31311090/155018454-bf4c1ab6-606a-437d-a350-2eaf7ed5f3f8.png)

**Comment by jamesjuett** [comment]
`private` and `public` are indeed not supported yet. `const` can exist on the types of member functions:
![image](https://user-images.githubusercontent.com/14828215/155020121-81a96557-ab9e-48d8-bf08-9390c980580b.png)

But, it's not getting properly respected when a member is accessed. The issue appears that when I ported the codebase to TS a few years ago I must have mixed things up and member access is resulting in a `MemberObjectEntity` from lookup rather than a `MemberAccessEntity` (which can carry along the const). Working on a fix for this one now.

**Comment by jamesjuett** [comment]
Hm, actually `MemberAccessEntity` isn't the solution, instead `IdentifierExpression`, `DotExpression`, and `ArrorExpression` should just take care of member access taking on constness from the receiver object.
